config/routes.rb
ExpenseTracker::Application.routes.draw do
  root to: redirect("/expenses")

  resources :expenses

  get "/login", to: redirect("/auth/google")
  match "/auth/:provider/callback", to: 'sessions#create'

end

app/models/expense.rb
class Expense < ActiveRecord::Base
  attr_accessible :amount, :date, :description, :name

  belongs_to :created_by, class_name: "User"
  belongs_to :updated_by, class_name: "User"

  before_validation :set_default_values, on: :create

  validates :amount, :created_by, :date, :name, :updated_by, presence: true

  def date=(d)
    d = d.to_i if d.is_a?(String) && d =~ /\d+/
    d = Time.at(d).to_date if d.is_a?(Numeric)
    super
  end

private
  def set_default_values
    self.date ||= Date.today
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :provider, :uid

  has_many :expenses_created, class_name: "Expense", dependent: :nullify, foreign_key: :created_by_id
  has_many :expenses_updated, class_name: "Expense", dependent: :nullify, foreign_key: :updated_by_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

private
  def current_user
    return @current_user if defined?(@current_user)
    @current_user = User.find_by_id(cookies.signed[:user_id]) if cookies.signed[:user_id].present?
  end
  helper_method :current_user

  def require_user
    if current_user.blank?
      redirect_to :login
    end
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_filter :require_user

  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = Expense.order("date DESC")
    @total = Expense.sum(:amount)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @expenses }
    end
  end

  # GET /expenses/new
  # GET /expenses/new.json
  def new
    @expense = Expense.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @expense }
    end
  end

  # GET /expenses/1/edit
  def edit
    @expense = Expense.find(params[:id])
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(params[:expense])
    @expense.created_by = @expense.updated_by = current_user

    respond_to do |format|
      if @expense.save
        format.html { redirect_to :expenses, notice: 'Expense was successfully created.' }
        format.json { render json: @expense, status: :created, location: @expense }
      else
        format.html { render action: "new" }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /expenses/1
  # PUT /expenses/1.json
  def update
    @expense = Expense.find(params[:id])
    @expense.updated_by = current_user

    respond_to do |format|
      if @expense.update_attributes(params[:expense])
        format.html { redirect_to :expenses, notice: 'Expense was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense = Expense.find(params[:id])
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to expenses_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    if user = User.find_by_provider_and_uid(auth['provider'], auth['uid'])
      cookies.signed.permanent[:user_id] = user.id
      redirect_to :expenses
    else
      render text: "<pre>Not authenticated. Send Brian the following info:\n  provider: #{auth['provider']}\n  uid: #{auth['uid']}</pre>"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def include_manifest!
    @include_manifest = true
  end

  def include_manifest?
    !!@include_manifest
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/expenses/_form.html.haml
= simple_form_for(@expense) do |f|
  = f.input :name
  = f.input :amount
  = f.input :description
  = f.input :date unless @expense.new_record?
  = f.button :submit

app/views/expenses/edit.html.haml
%h1 Editing expense
= render 'form'

=link_to 'Back', expenses_path
|
=link_to 'Delete', @expense, confirm: "Delete this expense?", method: :delete

app/views/expenses/index.html.haml
%h1 Listing expenses

%p
  Total: #{number_to_currency @total}

%p= link_to 'New Expense', new_expense_path, class: "button"

%table.expenses
  %tr
    %th Name
    %th Amount
    %th Date
    %th.description Description
  - @expenses.each do |expense|
    %tr
      %td= link_to expense.name, [:edit, expense]
      %td= number_to_currency expense.amount
      %td= expense.date
      %td.description= expense.description

app/views/expenses/new.html.haml
%h1 New expense
= render 'form'
= link_to 'Back', expenses_path

app/views/layouts/application.html.haml
!!!
<html lang="en" #{raw "manifest='/application.manifest'" if include_manifest?}>
%head
  %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1", :name => "viewport"}/
  %title= content_for?(:title) ? yield(:title) : "Untitled"
  = stylesheet_link_tag    "application"
  = javascript_include_tag "application"
  = yield(:head)
  = csrf_meta_tags
%body{id: "#{controller_name}_controller", class: "#{params[:action]}_action"}
  - if Rails.env.development?
    / Brian is a spaz and keeps entering real info in dev server
    .alert-box.alert
      You're in development.
      %a.close{:href => ""} &times;
  .row
    .twelve.columns
      = yield